import Navbar from "@/components/modules/Navbar/Navbar";
import "./globals.css";
import AOSInit from "@/utils/aos";
import Footer from "@/components/modules/Footer/Footer";
import ScrollToTop from "@/utils/ScrollToTop";
import SignIn from "@/components/templates/SignIn/SignIn";
import NextCoffeeProvider from "@/components/context/NextCoffeeProvider";
import toast, { Toaster } from 'react-hot-toast';


export const metadata = {
  title: "صفحه اصلی - JamCoffee",
  description: "Generated by Jamjam",
  icons: { icon: "/images/coffee-image-1.jpg" }
};

export default function RootLayout(props) {
  const { children } = props;
  return (
    <html lang="fa" dir="rtl">
      <Toaster />
      <NextCoffeeProvider>

        <body >
          <div className='w-full relative flex flex-col items-center'>
            <Navbar />
            <div className="mt-28">
              <AOSInit />
              {children}
            </div>
            {/* <ScrollToTop /> */}
            {/* <SignIn /> */}
            <Footer />
          </div>
        </body>
      </NextCoffeeProvider>
    </html>


  );
}
