import Navbar from "@/components/modules/Navbar/Navbar";
import "./globals.css";
import AOSInit from "@/utils/aos";
import Footer from "@/components/modules/Footer/Footer";
import ScrollToTop from "@/utils/ScrollToTop";
import SignIn from "@/components/templates/SignIn";
import NextCoffeeProvider from "@/components/context/NextCoffeeProvider";



export const metadata = {
  title: "صفحه اصلی - JamCoffee",
  description: "Generated by Jamjam",
  icons: { icon: "/images/coffee-image-1.jpg" }
};

export default function RootLayout(props) {
  const { children } = props;
  props.params.isShow = "Hamediiii"
  console.log("Props in RootLayout", JSON.stringify(props.params));

  return (

    <html lang="fa" dir="rtl">
      <body >
        <div className='w-full relative flex flex-col items-center'>
          <NextCoffeeProvider>
            <Navbar />
            <div className="mt-28">
              <AOSInit />
              {children}
            </div>
            {/* <ScrollToTop /> */}
            {/* <SignIn /> */}
            <Footer />
          </NextCoffeeProvider>
        </div>
      </body>
    </html>


  );
}
